# Generated by Django 5.2.7 on 2025-11-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='valor_mensalidade',
            field=models.DecimalField(decimal_places=2, default=450.0, help_text='Valor fixo mensal da mensalidade deste aluno', max_digits=10, verbose_name='Valor da Mensalidade'),
        ),
    ]
